### ISSUE TITLE
[FEATURE] First executable version

### ISSUE THREAD

**Issue by Sombeyyy** [Sombeyyy/MagicEnchants#1]
The plugin should be able to be compiled and successfully loaded from the server

**Tasks:**

- [x] create main class
- [x] create plugin.yml
- [x] log messages while loading/unloading
